name:                mojprojekat
version:             0.1.0.0
github:              "githubuser/mojprojekat"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mojprojekat#readme>

dependencies:
  - base >=4.7 && <5
  - aeson
  - bytestring
  - esqueleto
  - monad-logger
  - mtl
  - persistent
  - persistent-postgresql
  - persistent-template
  - servant
  - servant-client
  - servant-server
  - text
  - time
  - transformers
  - warp
  - wai-cors
  - libiserv
library:
  source-dirs: src

executables:
  run-server:
    main:                RunServer.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is RunServer
    dependencies:
    - mojprojekat
  migrate-db:
    main:                MigrateDB.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is MigrateDB
    dependencies:
    - mojprojekat


tests:
  mojprojekat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mojprojekat
